modules/epics/src/test/scala/engage/epics/TestEpicsServer.scala, modules/server/src/main/scala/engage/server/tcs/TcsBaseController.scala, modules/server/src/main/scala/engage/server/tcs/TcsBaseControllerEpics.scala, modules/server/src/main/scala/engage/server/tcs/TcsBaseControllerSim.scala, modules/server/src/main/scala/engage/server/tcs/TcsEpicsSystem.scala, modules/server/src/test/scala/engage/server/tcs/TcsBaseControllerEpicsSpec.scala, modules/server/src/test/scala/engage/server/tcs/TestTcsEpicsSystem.scala, project/Settings.scala
Configure main science target in TCS.
=> SourceA config

modules/model/shared/src/main/scala/navigate/model/NavigateCommand.scala, modules/server/src/main/scala/navigate/server/NavigateEngine.scala, modules/server/src/main/scala/navigate/server/tcs/SlewConfig.scala, modules/server/src/main/scala/navigate/server/tcs/TcsBaseController.scala, modules/server/src/main/scala/navigate/server/tcs/TcsBaseControllerEpics.scala, modules/server/src/main/scala/navigate/server/tcs/TcsBaseControllerSim.scala, modules/server/src/main/scala/navigate/server/tcs/TcsEpicsSystem.scala, modules/server/src/test/scala/navigate/server/tcs/TcsBaseControllerEpicsSpec.scala, modules/server/src/test/scala/navigate/server/tcs/TestTcsEpicsSystem.scala, modules/web/server/src/main/resources/NewTCC.graphql, modules/web/server/src/main/scala/navigate/web/server/http4s/NavigateMappings.scala, modules/web/server/src/test/scala/navigate/web/server/http4s/NavigateMappingsTest.scala
Added oiwfsTarget to slew command and also as an isolated command, including unit tests
=> Added oiwfsTarget

modules/stateengine/src/main/scala/navigate/stateengine/StateEngine.scala
The bug was that input events were inserted inside individual streams to be processed in a joined stream of streams, which does not guarantee that they will be processed in order. The solution was to add a separate `Queue` for inputs events.
=> Fixed bug that could cause out-of-order processing of input events.

.gitignore, README.md, app/navigate-server/src/main/resources/conf/app.conf, app/navigate-server/src/main/resources/systemd/navigate-server.env, app/navigate-server/src/main/resources/systemd/navigate-server.service, build.sbt, modules/web/server/src/main/scala/navigate/web/server/common/LogInitialization.scala, modules/web/server/src/main/scala/navigate/web/server/common/StaticRoutes.scala, modules/web/server/src/main/scala/navigate/web/server/common/package.scala, modules/web/server/src/main/scala/navigate/web/server/http4s/WebServerLauncher.scala, modules/web/server/src/test/scala/navigate/web/server/http4s/NavigateMappingsTest.scala, project/AppsCommon.scala
Create a deployable tarball with the server serving the UI. See README.md.
=> All-in-one deployment

modules/epics/src/main/scala/navigate/epics/EpicsService.scala, modules/server/src/main/scala/navigate/server/tcs/TcsBaseControllerEpics.scala, modules/server/src/main/scala/navigate/server/tcs/TcsChannels.scala, modules/server/src/main/scala/navigate/server/tcs/TcsEpicsSystem.scala, modules/server/src/main/scala/navigate/server/tcs/TelescopeGuideConfig.scala, modules/server/src/main/scala/navigate/server/tcs/package.scala, modules/server/src/test/scala/navigate/server/tcs/TcsBaseControllerEpicsSpec.scala, modules/server/src/test/scala/navigate/server/tcs/TestTcsEpicsSystem.scala, modules/web/server/src/main/resources/NewTCC.graphql, modules/web/server/src/main/scala/navigate/web/server/http4s/NavigateMappings.scala, modules/web/server/src/test/scala/navigate/web/server/http4s/NavigateMappingsTest.scala
This PR adds a parameter to configure guiders to set all gains to 0 as is usual for day time tests
=> Guider gains

modules/server/src/main/scala/navigate/server/tcs/GuideState.scala, modules/server/src/main/scala/navigate/server/tcs/TcsBaseControllerEpics.scala, modules/server/src/main/scala/navigate/server/tcs/TcsBaseControllerSim.scala, modules/server/src/main/scala/navigate/server/tcs/TcsEpicsSystem.scala, modules/server/src/main/scala/navigate/server/tcs/TcsNorthControllerSim.scala, modules/server/src/main/scala/navigate/server/tcs/TcsSouthControllerSim.scala, modules/server/src/test/scala/navigate/server/tcs/TcsBaseControllerEpicsSuite.scala, modules/web/server/src/main/resources/NewTCC.graphql, modules/web/server/src/main/scala/navigate/web/server/http4s/encoder/package.scala, modules/web/server/src/test/scala/navigate/web/server/http4s/NavigateMappingsTest.scala
API now includes state for PWFS1, PWFS2 and OIWFS.
=> Implemented WFS state in API.

modules/server/src/main/scala/navigate/server/tcs/TcsBaseController.scala, modules/server/src/main/scala/navigate/server/tcs/TcsBaseControllerEpics.scala, modules/server/src/main/scala/navigate/server/tcs/TcsChannels.scala, modules/server/src/main/scala/navigate/server/tcs/TcsEpicsSystem.scala, modules/server/src/test/scala/navigate/server/tcs/TcsBaseControllerEpicsSuite.scala, modules/server/src/test/scala/navigate/server/tcs/TestTcsEpicsSystem.scala, modules/web/server/src/main/resources/NewTCC.graphql, modules/web/server/src/main/scala/navigate/web/server/http4s/NavigateMappings.scala, modules/web/server/src/test/scala/navigate/web/server/http4s/NavigateMappingsTest.scala
Select the proper OI when slewing the telescope.
=> OI Selection

.scalafix-common.conf, .scalafmt-common.conf, .scalafmt.conf, modules/epics/src/main/scala/navigate/epics/Channel.scala, modules/epics/src/main/scala/navigate/epics/RemoteChannel.scala, modules/epics/src/main/scala/navigate/epics/package.scala, modules/epics/src/test/scala/navigate/epics/ChannelSpec.scala, modules/epics/src/test/scala/navigate/epics/EpicsServiceSpec.scala, modules/epics/src/test/scala/navigate/epics/EpicsSystemSpec.scala, modules/epics/src/test/scala/navigate/epics/TestEpicsServer.scala, modules/epics/src/test/scala/navigate/epics/VerifiedEpicsSpec.scala, modules/server/src/main/scala/navigate/server/NavigateEngine.scala, modules/server/src/main/scala/navigate/server/tcs/WfsEpicsSystem.scala, modules/web/server/src/main/scala/navigate/web/server/common/StaticRoutes.scala, modules/web/server/src/main/scala/navigate/web/server/http4s/NavigateMappings.scala, modules/web/server/src/main/scala/navigate/web/server/http4s/ProxyBuilder.scala, modules/web/server/src/test/scala/navigate/web/server/http4s/NavigateMappingsTest.scala, project/Settings.scala, project/plugins.sbt
Updated mouse, scalafmt, munit-cats-effect and sbt-lucuma-app. I left gracke update out, because it will take a bit more work.
=> Updated several libraries.

modules/server/src/main/scala/navigate/server/NavigateEngine.scala, modules/server/src/main/scala/navigate/server/Systems.scala, modules/server/src/main/scala/navigate/server/tcs/TcsBaseController.scala, modules/server/src/main/scala/navigate/server/tcs/TcsBaseControllerEpics.scala, modules/server/src/main/scala/navigate/server/tcs/TcsBaseControllerSim.scala, modules/server/src/main/scala/navigate/server/tcs/TcsNorthControllerSim.scala, modules/server/src/main/scala/navigate/server/tcs/TcsSouthControllerSim.scala, modules/server/src/main/scala/navigate/server/tcs/WfsChannels.scala, modules/server/src/main/scala/navigate/server/tcs/WfsEpicsSystem.scala, modules/server/src/test/scala/navigate/server/tcs/TcsBaseControllerEpicsSuite.scala, modules/server/src/test/scala/navigate/server/tcs/TestWfsEpicsSystem.scala, modules/web/server/src/main/resources/app.conf, modules/web/server/src/test/scala/navigate/web/server/http4s/NavigateMappingsTest.scala
Values are now read from EPICS channels. I also added the possibility to have different behaviors for North and South TCS (although for now they share the same implementation)
=> Implemented reading guide quality values from real systems.

modules/server/src/main/scala/navigate/server/Systems.scala
I only fixed it for GS in my previous PR. Here is the fix for GN.
=> Fixed OIWFS channels for GN.

project/Settings.scala
Updated to use navigate-ui v0.1.3
=> Updated UI version.

modules/server/src/main/scala/navigate/server/tcs/AgsEpicsSystem.scala
The problem was that OIWFS follow state (On/Off) was different from P1 and P2 state (ON/OFF)
=> Follow state decoding is now impervious to case variants.

modules/server/src/main/scala/navigate/server/Systems.scala, modules/server/src/main/scala/navigate/server/tcs/WfsChannels.scala, modules/server/src/main/scala/navigate/server/tcs/WfsEpicsSystem.scala
I was using the wrong channel for OIWFS.
=> Fixed OIWFS gains reset.

modules/server/src/main/scala/navigate/server/acm/Encoder.scala, modules/server/src/main/scala/navigate/server/tcs/TcsBaseControllerEpics.scala, modules/server/src/main/scala/navigate/server/tcs/TcsEpicsSystem.scala, modules/server/src/test/scala/navigate/server/tcs/TcsBaseControllerEpicsSuite.scala
Main problem was the case of the source label for M1 and M2 sources
=> SC-3817 Implemented fix for m2 guide config problem

modules/model/src/main/scala/navigate/model/NavigateCommand.scala, modules/model/src/main/scala/navigate/model/enums/AoFoldPosition.scala, modules/model/src/main/scala/navigate/model/enums/HrwfsPickupPosition.scala, modules/model/src/main/scala/navigate/model/enums/LightSource.scala, modules/server/src/main/scala/navigate/server/NavigateEngine.scala, modules/server/src/test/scala/navigate/server/tcs/TcsBaseControllerEpicsSuite.scala, modules/web/server/src/main/resources/NewTCC.graphql, modules/web/server/src/main/scala/navigate/web/server/http4s/NavigateMappings.scala, modules/web/server/src/test/scala/navigate/web/server/http4s/NavigateMappingsSuite.scala
Added light path configuration mutation to backend API.
Implemented tests for light path configuration.
Fixed some bugs.
=> SC-3284 Light path configuration included in backend API.

modules/server/src/main/scala/navigate/server/epicsdata/NodState.scala, modules/server/src/main/scala/navigate/server/tcs/M2BeamConfig.scala, modules/server/src/main/scala/navigate/server/tcs/TcsBaseControllerEpics.scala, modules/server/src/main/scala/navigate/server/tcs/TcsChannels.scala, modules/server/src/main/scala/navigate/server/tcs/TcsEpicsSystem.scala, modules/server/src/test/scala/navigate/server/tcs/TcsBaseControllerEpicsSuite.scala, modules/server/src/test/scala/navigate/server/tcs/TestTcsEpicsSystem.scala
I rewrote the code that configures M2 guiding. Hopefully I understood the Tcl code correctly this time.
=> SC-4386 Fixed M2 tip/tilt guide configuration.

.github/workflows/ci.yml, build.sbt, modules/server/src/main/scala/navigate/server/NavigateEngine.scala, modules/server/src/main/scala/navigate/server/tcs/AcquisitionCameraEpicsSystem.scala, modules/server/src/main/scala/navigate/server/tcs/OiwfsEpicsSystem.scala, modules/server/src/main/scala/navigate/server/tcs/TcsBaseControllerEpics.scala, modules/server/src/main/scala/navigate/server/tcs/WfsEpicsSystem.scala, modules/server/src/test/scala/navigate/server/tcs/TestAcquisitionCameraEpicsSystem.scala, modules/server/src/test/scala/navigate/server/tcs/TestAgsEpicsSystem.scala, modules/server/src/test/scala/navigate/server/tcs/TestCrcsEpicsSystem.scala, modules/server/src/test/scala/navigate/server/tcs/TestMcsEpicsSystem.scala, modules/server/src/test/scala/navigate/server/tcs/TestOiwfsEpicsSystem.scala, modules/server/src/test/scala/navigate/server/tcs/TestScsEpicsSystem.scala, modules/server/src/test/scala/navigate/server/tcs/TestWfsEpicsSystem.scala, project/Settings.scala
I had to manually fix several type constraints that were giving warnings in Scala 3.6.2
=> Updated to scala 3.6.2, lucuma-schemas to 0.113.0.

modules/server/src/main/scala/navigate/server/tcs/TcsBaseControllerEpics.scala, modules/server/src/main/scala/navigate/server/tcs/TcsEpicsSystem.scala, modules/server/src/test/scala/navigate/server/tcs/TcsBaseControllerEpicsSuite.scala
I opted for relying on lucuma Angle format functions.
=> SC-4683 Fixed issue with coordinates conversion to string.

modules/web/server/src/main/scala/navigate/web/server/http4s/GraphQlRoutes.scala, modules/web/server/src/main/scala/navigate/web/server/http4s/NavigateMappings.scala, modules/web/server/src/main/scala/navigate/web/server/http4s/WebServerLauncher.scala, modules/web/server/src/test/scala/navigate/web/server/http4s/NavigateMappingsSuite.scala
https://github.com/user-attachments/assets/18f643cb-3535-411c-a602-5646bc06d3ce
=> Keep last 30 log messages buffered to send to logMessage subscription start

modules/model/src/main/scala/navigate/model/config/WebServerConfiguration.scala, modules/web/server/src/main/scala/navigate/web/server/config/package.scala, modules/web/server/src/main/scala/navigate/web/server/http4s/WebServerLauncher.scala, project/Settings.scala
Probably needs fairly thorough testing for any subtle differences between Ember and Blaze. Everything worked locally, however
=> Switch to Http4s Ember server

deploy/src/main/resources/conf/app.conf, modules/web/server/src/main/resources/app.conf
Deployment is not working, I think I need to add these
=> Conf for deployment

modules/schema-util/src/main/scala/edu/gemini/schema/util/SourceResolver.scala, modules/web/server/src/main/scala/navigate/web/server/http4s/WebServerLauncher.scala, project/Settings.scala
Needs https://github.com/gemini-hlsw/navigate-ui/pull/593
=> Read frontend version and print in startup

modules/server/src/main/scala/navigate/server/NavigateEngine.scala, modules/server/src/main/scala/navigate/server/tcs/TcsBaseControllerEpics.scala, modules/server/src/test/scala/navigate/server/NavigateEngineSpec.scala, modules/server/src/test/scala/navigate/server/tcs/TcsBaseControllerEpicsSuite.scala, modules/web/server/src/test/scala/navigate/web/server/http4s/NavigateMappingsSuite.scala
This fixes an edge case, but it is probably not the reason the tests failed.
=> SC-5265 Fixed minor bug in gacq application.

modules/server/src/main/scala/navigate/server/tcs/WfsEpicsSystem.scala, modules/server/src/test/scala/navigate/server/tcs/TcsBaseControllerEpicsSuite.scala
I found that the logic was inverted.
=> SC-4685 Fixed centroid value decoding.

modules/server/src/main/scala/navigate/server/tcs/FocalPlaneOffset.scala, modules/server/src/main/scala/navigate/server/tcs/HandsetAdjustment.scala, modules/server/src/main/scala/navigate/server/tcs/TargetOffsets.scala, modules/web/server/src/main/resources/navigate.graphql, modules/web/server/src/main/scala/navigate/web/server/http4s/GraphQlRoutes.scala, modules/web/server/src/main/scala/navigate/web/server/http4s/NavigateMappings.scala, modules/web/server/src/main/scala/navigate/web/server/http4s/TopicManager.scala, modules/web/server/src/main/scala/navigate/web/server/http4s/WebServerLauncher.scala, modules/web/server/src/main/scala/navigate/web/server/http4s/encoder/package.scala, modules/web/server/src/test/scala/navigate/web/server/http4s/NavigateMappingsSuite.scala
This PR expands the server API to include the mutations and queries required for the target, pointing and instrument origin handsets.
=> SC-3259 Server GraphQL API for handsets.

modules/server/src/main/scala/navigate/server/tcs/TcsChannels.scala
=> SC-6117 Fixed definition of coma selection channel.

build.sbt, modules/server/src/main/scala/navigate/server/tcs/TcsBaseControllerEpics.scala, modules/server/src/test/scala/navigate/server/tcs/TcsBaseControllerEpicsSuite.scala, modules/web/server/src/main/resources/navigate.graphql, modules/web/server/src/main/scala/navigate/web/server/http4s/NavigateMappings.scala, modules/web/server/src/test/scala/navigate/web/server/http4s/NavigateMappingsSuite.scala
I corrected the angle calculations for the different alignments. I was using a standard polar correction but, for example, in RA/Dec system 0º  is North (0, +Dec) and 90º is West (+RA, 0).
=> SC-6186 Adjusted angle calculation for the different alignments.

modules/model/src/main/scala/navigate/model/NavigateCommand.scala, modules/model/src/main/scala/navigate/model/PwfsMechsState.scala, modules/model/src/main/scala/navigate/model/enums/PwfsFieldStop.scala, modules/model/src/main/scala/navigate/model/enums/PwfsFilter.scala, modules/server/src/main/scala/navigate/server/NavigateEngine.scala, modules/server/src/main/scala/navigate/server/tcs/AgsChannels.scala, modules/server/src/main/scala/navigate/server/tcs/AgsEpicsSystem.scala, modules/server/src/main/scala/navigate/server/tcs/TcsBaseController.scala, modules/server/src/main/scala/navigate/server/tcs/TcsBaseControllerEpics.scala, modules/server/src/main/scala/navigate/server/tcs/TcsBaseControllerSim.scala, modules/server/src/main/scala/navigate/server/tcs/TcsChannels.scala, modules/server/src/main/scala/navigate/server/tcs/TcsEpicsSystem.scala, modules/server/src/test/scala/navigate/server/tcs/TcsBaseControllerEpicsSuite.scala, modules/server/src/test/scala/navigate/server/tcs/TestAgsEpicsSystem.scala, modules/server/src/test/scala/navigate/server/tcs/TestTcsEpicsSystem.scala, modules/web/server/src/main/resources/navigate.graphql, modules/web/server/src/main/scala/navigate/web/server/http4s/GraphQlRoutes.scala, modules/web/server/src/main/scala/navigate/web/server/http4s/NavigateMappings.scala, modules/web/server/src/main/scala/navigate/web/server/http4s/TopicManager.scala, modules/web/server/src/main/scala/navigate/web/server/http4s/WebServerLauncher.scala, modules/web/server/src/main/scala/navigate/web/server/http4s/encoder/package.scala, modules/web/server/src/test/scala/navigate/web/server/http4s/NavigateMappingsSuite.scala
PWFS1 and PWFS2 have the same mechanisms, a filter wheel and a field stop wheel, both with the same components. Because of that, most of the code is common to both.
=> Sc 6539 pwfs components control
